controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
traitement:
    path: /
    controller: App\Controller\TraitementController::index
